// Generated by scripts/sync-resume.mjs from the resume PDF.
// Links, OSS, and projects live in content/profile.overrides.json.

export const profile = {
  name: "Sarvodaya Kumar",
  title: "Cloud Backend Developer",
  specialty: "Bangalore, Karnataka · Golang (Advanced) · C (Intermediate) · Docker",
  tagline: "I design and ship production backends on Azure — Go services, Kubernetes, and Terraform.",
  avatar: "/portraits/front.png",
  experienceYears: "5+",
  status: "Open to collaboration",
  resumeUrl: "/resume.pdf",
  typingLines: ["Senior Development Engineer @ Calsoft Pvt Limited", "Open source: sensu-go and terraform-provider-aquasec", "Open to senior engineering conversations"],
  links: {
    linkedin: "https://linkedin.com/in/sarvodaya",
    email: "sarvodaya.kumar@outlook.com",
    github: "https://github.com/sarvodayaKumar",
    workGithub: "https://github.com/sarvodaya-kumar-26",
    instagram: "https://www.instagram.com/_s.a.r.v.o_/",
    phone: "tel:+91-9776159842"
  },
  currentFocus: {
    role: "Senior Development Engineer, Calsoft Pvt Limited",
    contributions: "aquasecurity/terraform-provider-aquasec, sensu/sensu-go, sensu/core, sensu/etcd, sensu/sensu-packaging",
    workHandle: "@sarvodaya-kumar-26",
    techStack: "Golang (Advanced), C (Intermediate), Docker, Kubernetes",
    focusAreas: "Developed and extended core provider resource support in Go by contributing to the v0.12.x release series of the Aqua Terraform…"
  },
  about: ["Senior Software Engineer with 5+ years of experience in network performance optimization, microservices architecture, and DevOps practices. Skilled in automating CI/CD pipelines, containerization with Docker, orchestrating with Kubernetes and building terraform infrastructure. Expertise in cloud technologies. Adept at root cause analysis, performance monitoring, and enhancing security through advanced encryption algorithms. Proven ability to collaborate effectively in cross-functional teams and deliver scalable, reliable solutions in high-performance environments.", "Alongside product work, I contribute upstream in Go to Sensu (observability engine, core libraries, etcd integration, packaging) and Aqua Security's Terraform provider — resources, REST clients, and acceptance tests.", "Architected & implemented cloud-native microservices using Golang, Kubernetes, and Docker, applying robust software design principles and data structures & algorithms (DSA) to ensure scalability, maintainability, and performance."],
  expertise: [
    {
      icon: "code",
      title: "Backend systems",
      items: ["Golang (Advanced) · C (Intermediate)", "RESTful APIs, gRPC, Postgres", "Production microservices and API design"]
    },
    {
      icon: "cloud",
      title: "Cloud & infrastructure",
      items: ["Azure", "Azure DevOps", "Terraform"]
    },
    {
      icon: "activity",
      title: "Delivery & platforms",
      items: ["Docker", "Kubernetes", "Helm"]
    },
    {
      icon: "shield",
      title: "Observability & security",
      items: ["Prometheus", "Grafana", "Trivy"]
    }
  ],
  contributions: [
    {
      repo: "aquasecurity/terraform-provider-aquasec",
      url: "https://github.com/aquasecurity/terraform-provider-aquasec",
      org: "Aqua Security",
      focus: "Custom resources, REST APIs, API-key auth, and acceptance tests in Go",
      prs: ["374", "373", "372", "371", "370", "369"]
    },
    {
      repo: "sensu/sensu-go",
      url: "https://github.com/sensu/sensu-go",
      org: "Sensu",
      focus: "Event handlers, check filters, and telemetry pipelines",
      prs: ["5176", "5171", "5170", "5169"],
      issues: ["5175", "5173", "5172"]
    },
    {
      repo: "sensu/core",
      url: "https://github.com/sensu/core",
      org: "Sensu",
      focus: "Core engine abstractions and pipeline interfaces",
      prs: ["53"],
      issues: ["54"]
    },
    {
      repo: "sensu/etcd",
      url: "https://github.com/sensu/etcd",
      org: "Sensu",
      focus: "State synchronization and etcd cluster orchestration",
      prs: []
    },
    {
      repo: "sensu/sensu-packaging",
      url: "https://github.com/sensu/sensu-packaging",
      org: "Sensu",
      focus: "Build automation and packaging pipeline maintenance",
      prs: []
    }
  ],
  openSource: [
    {
      type: "oss",
      role: "Open Source Contributor",
      company: "Sensu",
      period: "2025 – Present",
      focus: "Observability engine: handlers, pipelines, core libraries, and packaging",
      highlights: ["Contributed to sensu/sensu-go — event handlers, check filters, and telemetry agent pipelines", "Extended sensu/core with engine abstractions and pipeline interfaces in Go", "Worked on sensu/etcd cluster state sync and sensu/sensu-packaging release automation", "Opened and landed PRs and issues across the Sensu Go stack (work handle @sarvodaya-kumar-26)"]
    },
    {
      type: "oss",
      role: "Open Source Contributor",
      company: "Aqua Security",
      period: "2025 – Present",
      focus: "terraform-provider-aquasec — IaC for the Aqua platform",
      highlights: ["Implemented custom Terraform resources and REST API clients in Go", "Added acceptance tests with terraform-plugin-testing (plan / apply / destroy)", "Shipped API key authorization and resources for serverless apps, log management, and monitoring", "Landed multiple provider PRs in the v0.12.x series"]
    }
  ],
  employment: [
    {
      role: "Senior Development Engineer",
      company: "Calsoft Pvt Limited",
      period: "June 2025 – Present",
      focus: "Developed and extended core provider resource support in Go by contributing to the v0.12.x…",
      highlights: ["Developed and extended core provider resource support in Go by contributing to the v0.12.x release series of the Aqua Terraform provider—adding capabilities for managing complex platform entities such as Serverless Applications, Log Management, and Monitoring Systems, enabling customers to model comprehensive infrastructure state via IaC.", "Optimized Terraform acceptance test coverage and framework usage (terraform-plugin-testing) to support new resource lifecycle validation (Create/Read/Update/Delete) workflows and prevent regressions during plan/apply/destroy operations across provider releases.", "Enhanced provider API reliability by driving API client maturation in Go—implementing and refining client support for newly introduced endpoints (e.g., Log Management, Monitoring Systems), increasing alignment between Terraform schema and upstream REST APIs.", "Designed and implemented Terraform state drift identification functionality in Go by analyzing real-world state inconsistencies and automating detection of configuration vs. actual infrastructure drift, improving reliability of desired vs. actual state verification.", "Authored comprehensive acceptance tests for the Terraform provider using the terraform-plugin-testing framework (e.g., TestAccXxx patterns), validating full Terraform lifecycle workflows—plan, apply, and destroy to ensure provider stability and real-world reliability.", "Collaborated cross-functionally to integrate REST API enhancements, test automation, and CI pipeline improvements, aligning with customer requirements while maintaining high code quality and release cadence.", "Developed API key authorization feature in the Terraform Provider Aqua Security, enabling secure programmatic access to Aqua Security APIs."],
      type: "employment"
    },
    {
      role: "Senior Project Engineer",
      company: "Wipro Limited",
      period: "March 2021 – June 2025",
      focus: "Architected & implemented cloud-native microservices using Golang, Kubernetes, and Docker,…",
      highlights: ["Architected & implemented cloud-native microservices using Golang, Kubernetes, and Docker, applying robust software design principles and data structures & algorithms (DSA) to ensure scalability, maintainability, and performance.", "Designed and developed RESTful APIs for inter-service and external communication, optimizing resource usage and reducing latency.", "Engineered advanced encryption layers ensuring secure microservice interactions, reinforcing best practices in secure design and API communication.", "Streamlined CI/CD pipelines using Azure DevOps with Terraform and Jenkins, automating build, test, and deployment flows to deliver fast, reliable releases—a practice highlighted as essential for microservices roles.", "Deployed and managed infrastructure on Azure, deploying microservices through container orchestration (Kubernetes), aligning with cloud-native practices.", "Extended Terraform with custom Go-based providers and modules, driving infrastructure as code (IaC) to automate provisioning and maintain consistency across environments.", "Applied core software design principles (e.g. modular architecture, SOLID, proper layering) across microservices, ensuring clean separation of concerns, scalability, and maintainability.", "Reduced release cycle times and increased efficiency by 11%, thanks to CI/CD automation, container orchestration, and DevOps tooling."],
      type: "employment"
    }
  ],
  techStack: {
    Languages: ["Golang (Advanced)", "C (Intermediate)"],
    "DevOps & CI/CD": ["Docker", "Kubernetes", "Helm", "Jenkins", "CI/CD pipelines", "Bash", "Maven", "YAML scripting", "Git"],
    "Cloud & Infrastructure as Code": ["Azure", "Azure DevOps", "Terraform", "Ansible"],
    "Monitoring & Security": ["Prometheus", "Grafana", "Trivy", "Tenable", "Grype", "JFrog Artifactory", "Azure APIM", "Linux (RHEL 7/8, Ubuntu)", "Networking fundamentals"],
    "APIs & Scripting": ["RESTful APIs", "gRPC", "Postgres"]
  },
  stats: [
    {
      value: "5+",
      label: "Years in production"
    },
    {
      value: "5",
      label: "OSS repositories"
    },
    {
      value: "Golang (Advanced)",
      label: "Primary language"
    },
    {
      value: "Bangalore",
      label: "Based in"
    }
  ],
  experience: [
    {
      type: "oss",
      role: "Open Source Contributor",
      company: "Sensu",
      period: "2025 – Present",
      focus: "Observability engine: handlers, pipelines, core libraries, and packaging",
      highlights: ["Contributed to sensu/sensu-go — event handlers, check filters, and telemetry agent pipelines", "Extended sensu/core with engine abstractions and pipeline interfaces in Go", "Worked on sensu/etcd cluster state sync and sensu/sensu-packaging release automation", "Opened and landed PRs and issues across the Sensu Go stack (work handle @sarvodaya-kumar-26)"]
    },
    {
      type: "oss",
      role: "Open Source Contributor",
      company: "Aqua Security",
      period: "2025 – Present",
      focus: "terraform-provider-aquasec — IaC for the Aqua platform",
      highlights: ["Implemented custom Terraform resources and REST API clients in Go", "Added acceptance tests with terraform-plugin-testing (plan / apply / destroy)", "Shipped API key authorization and resources for serverless apps, log management, and monitoring", "Landed multiple provider PRs in the v0.12.x series"]
    },
    {
      role: "Senior Development Engineer",
      company: "Calsoft Pvt Limited",
      period: "June 2025 – Present",
      focus: "Developed and extended core provider resource support in Go by contributing to the v0.12.x…",
      highlights: ["Developed and extended core provider resource support in Go by contributing to the v0.12.x release series of the Aqua Terraform provider—adding capabilities for managing complex platform entities such as Serverless Applications, Log Management, and Monitoring Systems, enabling customers to model comprehensive infrastructure state via IaC.", "Optimized Terraform acceptance test coverage and framework usage (terraform-plugin-testing) to support new resource lifecycle validation (Create/Read/Update/Delete) workflows and prevent regressions during plan/apply/destroy operations across provider releases.", "Enhanced provider API reliability by driving API client maturation in Go—implementing and refining client support for newly introduced endpoints (e.g., Log Management, Monitoring Systems), increasing alignment between Terraform schema and upstream REST APIs.", "Designed and implemented Terraform state drift identification functionality in Go by analyzing real-world state inconsistencies and automating detection of configuration vs. actual infrastructure drift, improving reliability of desired vs. actual state verification.", "Authored comprehensive acceptance tests for the Terraform provider using the terraform-plugin-testing framework (e.g., TestAccXxx patterns), validating full Terraform lifecycle workflows—plan, apply, and destroy to ensure provider stability and real-world reliability.", "Collaborated cross-functionally to integrate REST API enhancements, test automation, and CI pipeline improvements, aligning with customer requirements while maintaining high code quality and release cadence.", "Developed API key authorization feature in the Terraform Provider Aqua Security, enabling secure programmatic access to Aqua Security APIs."],
      type: "employment"
    },
    {
      role: "Senior Project Engineer",
      company: "Wipro Limited",
      period: "March 2021 – June 2025",
      focus: "Architected & implemented cloud-native microservices using Golang, Kubernetes, and Docker,…",
      highlights: ["Architected & implemented cloud-native microservices using Golang, Kubernetes, and Docker, applying robust software design principles and data structures & algorithms (DSA) to ensure scalability, maintainability, and performance.", "Designed and developed RESTful APIs for inter-service and external communication, optimizing resource usage and reducing latency.", "Engineered advanced encryption layers ensuring secure microservice interactions, reinforcing best practices in secure design and API communication.", "Streamlined CI/CD pipelines using Azure DevOps with Terraform and Jenkins, automating build, test, and deployment flows to deliver fast, reliable releases—a practice highlighted as essential for microservices roles.", "Deployed and managed infrastructure on Azure, deploying microservices through container orchestration (Kubernetes), aligning with cloud-native practices.", "Extended Terraform with custom Go-based providers and modules, driving infrastructure as code (IaC) to automate provisioning and maintain consistency across environments.", "Applied core software design principles (e.g. modular architecture, SOLID, proper layering) across microservices, ensuring clean separation of concerns, scalability, and maintainability.", "Reduced release cycle times and increased efficiency by 11%, thanks to CI/CD automation, container orchestration, and DevOps tooling."],
      type: "employment"
    }
  ],
  projects: [
    {
      name: "terraform-provider-aquasec",
      description: "Aqua Security Terraform provider — platform resources, APIs, and acceptance tests",
      url: "https://github.com/sarvodayaKumar/terraform-provider-aquasec",
      tags: ["Go", "Terraform", "Security"]
    },
    {
      name: "terraform-provider-dashboard",
      description: "Custom Terraform provider for dashboard resources over a REST API",
      url: "https://github.com/sarvodayaKumar/terraform-provider-dashboard",
      tags: ["Go", "Terraform", "API"]
    },
    {
      name: "infrastructure",
      description: "Reusable Terraform modules for cloud provisioning",
      url: "https://github.com/sarvodayaKumar/infrastructure",
      tags: ["Terraform", "Azure"]
    },
    {
      name: "deployment",
      description: "Delivery pipelines with promotion gates and scanning",
      url: "https://github.com/sarvodayaKumar/deployment",
      tags: ["CI/CD", "HCL"]
    },
    {
      name: "web_application",
      description: "Cloud-native application topology and container config",
      url: "https://github.com/sarvodayaKumar/web_application",
      tags: ["Kubernetes", "Azure"]
    }
  ],
  certifications: [
    {
      name: "Azure Fundamentals(AZ-900)",
      detail: "Issued by : Microsoft · Credential ID : 21634BE1265817EF · Certification number : 9A0443-1C1A3H · Issued May 2024",
      status: "completed"
    }
  ],
  education: {
    degree: "B.Tech in Electrical & Electronics Engineering",
    school: "Silicon Institute of Technology, Bhubaneswar",
    period: "August 2016 – August 2020"
  }
};
